### PR TITLE
Warren

### PR DESCRIPTION
**Pull request by michelleli94**

### CODE REVIEW

**Comment by michelleli94** [comment]
@cihtsliu Chris, will you review the change to connector.py and comment here with your approval of the change or suggest the change? Thank you.

**Comment by cihrsliu** [comment]
@michelleli94 There are a few errors in the new functions and a duplicated function in connector.py, and a bit more code needs to be added for it to work properly.

**Comment by michelleli94** [comment]
Thanks @cihtsliu . Will you be able to fix it? Since you had some backend functions for the purpose, will it make more sense to use your functions?

**Comment by michelleli94** [comment]
@cihtsliu @WarrenXiaGG I pull the code from Warren's branch, and got an error when trying to access profile-settings page after setting person id to 2

**Comment by cihrsliu** [comment]
@michelleli94 I can fix it by Friday

**Comment by michelleli94** [comment]
@cihtsliu That is great. Please fix it, then I will merge this into master before handling the others.

**Comment by michelleli94** [comment]
Warren will make the change based on master then issue a new pull request.

**Pull request closed without merging**
